---
# tasks file for elk-common
- name: add elasticsearch repo key
  rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
  become: true

- name: add repofile to /etc/yum.repos.d/
  copy:
    src:  elasticsearch.repo
    dest: /etc/yum.repos.d/elasticsearch.repo
    owner: root
    group: root
    mode: 0644
  become: true

