---
# tasks file for elasticsearch
- name: copy elasticsearch config file
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: 0660
  become: true
  notify: start elasticsearch

- name: install elasticsearch
  yum:
    name: elasticsearch
    state: present
  become: true
  notify: start elasticsearch 
