---
# tasks file for elasticsearch
- name: add elasticsearch repo key
  rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: add repofile to /etc/yum.repos.d/
  copy:
    src:  elasticsearch.repo
    dest: /etc/yum.repos.d/elasticsearch.repo
    owner: root
    group: root
    mode: 0644

- name: install elasticsearch
  yum:
    name: elasticsearch
    state: present
    
