---
- hosts: control
  gather_facts: true
  remote_user: echeadle
  tasks:
  - name: Ensure EPEL is enabled
    yum:
      name: epel-release
      state: present
    become: True
  - name: Ensure libselinux-python is present
    yum:
      name: libselinux-python
      state: present
    become: True
  - name: Ensure libsemanage-python is present
    yum:
      name: libsemanage-python
      state: present
    become: True
  - name: Update Local hosts
    yum:
      name: "*"
      state: latest
    when: ansible_os_family == 'RedHat' 
    become: True

